name: Build and push Flask-app container

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Authenticate with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install Azure CLI
      run: sudo apt-get install azure-cli

    - name: Set auto-install of extensions
      run: az config set extensions.dynamic_install=yes_without_prompt

    - name: Install Azure CLI ML
      run: az extension add -n azure-cli-ml

    - name: Attach workspace
      run: az ml folder attach -w ml-ws -g shim.yohan.2012-rg

    - name: Retrieve the model
      run: az ml model download -t "." --model-id "roberta-sequence:1"

    - name: Build flask-app container
      run: docker build -t guru2024/flask-ys:latest .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push flask-app container to Docker Hub
      run: docker push guru2024/flask-ys:latest

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_REGISTRY }}

    - name: Push flask-app container to GitHub Container Registry
      run: docker push ghcr.io/guru2024/flask-ys:latest
